export default [
  { title: 'Facebook', value: 'Facebook' },
  { title: 'Twitter', value: 'Twitter' },
  { title: 'Instagram', value: 'Instagram' },
  { title: 'LinkedIn', value: 'LinkedIn' },
  { title: 'YouTube', value: 'YouTube' },
  { title: 'Pinterest', value: 'Pinterest' },
  { title: 'Tumblr', value: 'Tumblr' },
  { title: 'Github', value: 'Github' },
  { title: 'Behance', value: 'Behance' },
  { title: 'Dribbble', value: 'Dribbble' },
  { title: 'Tiktok', value: 'Tiktok' },
  { title: 'Vimeo', value: 'Vimeo' },
  { title: 'Twitch', value: 'Twitch' },
  { title: 'Yelp', value: 'Yelp' },
  { title: 'Soundcloud', value: 'Soundcloud' },
  { title: 'Spotify', value: 'Spotify' },
  { title: 'Vk', value: 'Vk' },
  { title: 'Weibo', value: 'Weibo' },
  { title: 'Wechat', value: 'Wechat' },
]