const colors = require('tailwindcss/colors')
const withMT = require("@material-tailwind/react/utils/withMT");

module.exports = withMT({
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        moroi: {
          Myello: '#ffc513',
          dark: 'hsl(0, 0%, 21%)',
          grass: 'hsl(141, 53%, 53%)',
          yellow: 'hsl(48, 100%, 67%)',
          pinkdanger: 'hsl(348, 100%, 61%)',
          bluebutton: '#0079D3',
          greyblue: '#DAE0E6',
          Realred: '#ff0030',
          back: '#181818',
          stack: '#232323',
          gray: '#393e46',
        },
        'colorOne': '#3fabf3',
        'colorTwo': '#0794f2',
        'colorRed': '#ff0030',
        'colorThree': '#324b72',
        'colorFour': '#112950',
        'colorFive': '#E2E7ED',
        'colorSix': '#edeff2',
        'colorSeven': '#f8f9fb',
        'colorEight': '#ffffff',
        'bgheader': '#edf2f7',
        'iconcolor': 'rgba(7, 36, 86, 0.25)',
        'iconcolorhover': 'rgba(7, 36, 86, 0.5)',
        inherit: colors.inherit,
        current: colors.current,
        transparent: colors.transparent,
        black: colors.black,
        white: colors.white,
        slate: colors.slate,
        gray: colors.gray,
        zinc: colors.zinc,
        neutral: colors.neutral,
        stone: colors.stone,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      },
      dropShadow: {
        'topheader': 'inset 0px 0px 5px -2px #324b72',
      },
      boxShadow: {
        'blueShadow': '0 3px 5px 1px rgb(10 116 243 / 8%)',
        'FourCorner': '0px 0px 5px 1px rgb(10 116 243 / 8 %), 0px 2px 5px 1px rgb(10 116 243 / 8 %)',
        'blackShadow': '0px 2px 1px - 1px rgb(0 0 0 / 20 %), 0px 1px 1px 0px rgb(0 0 0 / 14 %), 0px 1px 3px 0px rgb(0 0 0 / 12 %)',
      },
      typography: ({ theme }) => ({
        colorThree: {
          css: {
            '--tw-prose-body': theme('colors.colorThree[800]'),
            '--tw-prose-headings': theme('colors.colorThree[900]'),
            '--tw-prose-lead': theme('colors.colorThree[700]'),
            '--tw-prose-links': theme('colors.colorThree[900]'),
            '--tw-prose-bold': theme('colors.colorThree[900]'),
            '--tw-prose-counters': theme('colors.colorThree[600]'),
            '--tw-prose-bullets': theme('colors.colorThree[400]'),
            '--tw-prose-hr': theme('colors.colorThree[300]'),
            '--tw-prose-quotes': theme('colors.colorThree[900]'),
            '--tw-prose-quote-borders': theme('colors.colorThree[300]'),
            '--tw-prose-captions': theme('colors.colorThree[700]'),
            '--tw-prose-code': theme('colors.colorThree[900]'),
            '--tw-prose-pre-code': theme('colors.colorThree[100]'),
            '--tw-prose-pre-bg': theme('colors.colorThree[900]'),
            '--tw-prose-th-borders': theme('colors.colorThree[300]'),
            '--tw-prose-td-borders': theme('colors.colorThree[200]'),
            '--tw-prose-invert-body': theme('colors.colorThree[200]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.colorThree[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.colorThree[400]'),
            '--tw-prose-invert-bullets': theme('colors.colorThree[600]'),
            '--tw-prose-invert-hr': theme('colors.colorThree[700]'),
            '--tw-prose-invert-quotes': theme('colors.colorThree[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.colorThree[700]'),
            '--tw-prose-invert-captions': theme('colors.colorThree[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.colorThree[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.colorThree[600]'),
            '--tw-prose-invert-td-borders': theme('colors.colorThree[700]'),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/line-clamp'),
  ],
})